### ISSUE TITLE
Unsupported plugin error for several plugins in dissect version 3.13

### ISSUE THREAD

**Issue by M1ra1B0T** [fox-it/dissect.target#573]
Hi,
I noticed that I do get multiple "Unsupported plugin" errors when using some target-query plugins with dissect version 3.13.
I did not receive this error with version 3.12.
```
target-query -f powershell_history,edge.history,iexplore.history,shellbags,userassist target.zip                                                   
2024-03-12T13:36:38.735818Z [warning  ] Velociraptor target PosixPath('target.zip') is compressed, which will slightly affect performance. Consider uncompressing the archive and passing the uncompressed folder to Dissect. [dissect.target.loaders.velociraptor]
2024-03-12T13:36:44.096870Z [error    ] <Target target.zip>: Unsupported plugin for powershell_history: No ConsoleHost_history.txt files found [dissect.target.target]
2024-03-12T13:36:45.050417Z [error    ] <Target target.zip>: Unsupported plugin for edge.history: No Chromium-based browser directories found [dissect.target.target]
2024-03-12T13:36:46.003782Z [error    ] <Target target.zip>: Unsupported plugin for iexplore.history: No Internet Explorer directories found [dissect.target.target]
2024-03-12T13:36:46.985390Z [error    ] <Target target.zip>: Unsupported plugin for shellbags: No shellbags found [dissect.target.target]
2024-03-12T13:36:46.989395Z [error    ] <Target target.zip>: Unsupported plugin for userassist: No UserAssist key found [dissect.target.target]
```
E.g. the powershell_history plugin states, that there is no `ConsoleHost_history.txt`, although there is:
```
unzip -l target.zip| grep "ConsoleHost_history.txt"
      499  2024-03-06 16:20   uploads/auto/C%3A/Users/user1/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadline/ConsoleHost_history.txt
       49  2019-05-20 17:12   uploads/auto/C%3A/Users/user2/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadline/ConsoleHost_history.txt
     6842  2021-09-10 10:46   uploads/auto/C%3A/Users/user3/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadline/ConsoleHost_history.txt
       14  2021-01-22 15:07   uploads/auto/C%3A/Users/user4/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadline/ConsoleHost_history.txt
       54  2023-10-30 18:20   uploads/auto/C%3A/Users/user5/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadline/ConsoleHost_history.txt
     1461  2024-03-07 12:00   uploads/auto/C%3A/Users/user6/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt
```
My target is a velociraptor collection of a windows server using the kapefiles artifact. Unfortunately I can not provide the original target, as it contains internal company information.

I also noticed that the output for some plugins differs between dissect version 3.12 and 3.13, if they are ran on the same target.
For the plugins `muicache` and `runkeys` I got fewer results. 
E.g. for the `runkeys` plugin I noticed that the entries from the `ntuser.dat` were not included, only from the `SOFTWARE` hive.

**Comment by Schamper** [comment]
Could you please share the instructions/configuration for replicating this Velociraptor collection? I'm trying it with a file I created using [this](https://github.com/fox-it/dissect.target/pull/558/files#diff-d21a3f7b5a8a12a1531cd0193f1d5d28eed550ad78782baaf78ce79f25b66631R63-R67) configuration but I can't reproduce it.

**Comment by M1ra1B0T** [comment]
Here is the config of the collector:
[config.txt](https://github.com/fox-it/dissect.target/files/14575116/config.txt)

**Comment by M1ra1B0T** [comment]
Thanks for the hint regarding the Velociraptor config. I made a new test collection with the new configuration and it worked. And regarding my old collection: I could not simply move all files from the old collection to `uploads/auto/C%3A` as `C%3A` I think is not supported by the `extract_drive_letter` function. I had to rename the folder to `%5C%5C.%5CC%3A`.

Might I suggest a better error handling regarding the supported Velociraptor collection format? Because currently you can run the tool on a collection "in the wrong format" and get (fewer) results. So it is easy to miss, that there is something wrong. And the hint, which Velociraptor config is supported, is not obvious for someone who uses the tool and does not look into the python code.

**Comment by Schamper** [comment]
I'll try to see if I can generate a test file with that configuration. I'll check how difficult it would be to support.

**Comment by Schamper** [comment]
#576 should fix this.

**Comment by M1ra1B0T** [comment]
I tried again with your commit and the `powershell_history` plugin on my velociraptor collection, but it still failed for me. I still got the error `Unsupported plugin for powershell_history: No ConsoleHost_history.txt files found [dissect.target.target]`. I will try to create a sample collection for you for testing.

**Comment by Schamper** [comment]
It would be amazing if you could provide me with a reference file for testing purposes, thanks!

**Comment by M1ra1B0T** [comment]
I think I have to apologize. Your fix indeed works. I forgot to git checkout ....... Seems I really needed the weekend.

**Comment by Schamper** [comment]
No problem! Happens to the best of us. We can go ahead with #576 in that case.
